### ISSUE TITLE
changes to the text

### ISSUE THREAD

**Issue by katjaluck** [BaderLab/openPIP#50]
There is a missing space in the header after "HuRI:"

It seems that the text on the home page is in two different colors, black (first paragraph) and grey (second paragraph). Can we choose one color?

In the introductory paragraphs in the "About" section, I had marked in parentheses where links can be placed to subsections further down the page. These comments still appear in the text and need to be deleted and the links placed.

The same is true for the paragraph on HI-III. There, too, needs a link to be placed to a subsection further down the page.

The link under "here" in the paragraph on HI-III points to our old website and absolutely needs to point to the downloads page of this new web portal.

On the About webpage, some text is in black, some in grey, please, unify.

On the Contact website: Please, remove the name Tong Hao from the general contact information as he now appears separately for the technical support. Can you write more specifically what type of questions/comments should be directed to Tong that fall into the Technical Support category and contrary to that, what questions should rather be directed to Gary? It's not really clear to me what the differences are...

**Comment by MoHelmy** [comment]
@katjaluck: please check the changes I made and if everything is ok, close this issue.

**Comment by katjaluck** [comment]
On the About page in the paragraph on HI-III can you please highlight the "here" in blue as well in the sentence: The list of genes being screened is provided here.

All the other changes requested are fixed. Many thanks!

**Comment by MoHelmy** [comment]
Done, also I make it open in new tab to be consistent with all other links.
