### ISSUE TITLE
malfunctioning download via email link

### ISSUE THREAD

**Issue by katjaluck** [BaderLab/openPIP#67]
I have tried to download the HI-III dataset but I do not get any email with the link for the download. It had worked in the past though.

**Comment by katjaluck** [comment]
It actually works when i use my gmail account but not with my dfci.harvard.edu account. It also did not go into my spam. Weird.

**Comment by MilesGithub** [comment]
I tried it out and it works with my gmail and school email accounts. Try it again and maybe check the settings for your dfci.harvard.edu email accounts.
